/**
 * routes/statistics.js
 * ─────────────────────────────────────────────────────────────────────────────
 * Statistics dashboard + recommendation endpoints.
 *
 *   GET  /statistics                       → renders the dashboard page
 *   GET  /statistics/purchase-order?days=N → JSON purchase-order recommendation
 *   GET  /statistics/production-tasks?days=N → JSON daily production-task plan
 *
 * Statistics data lives in services/statisticsService.js. PDF rendering is kept
 * inside this route file to avoid missing-module deployment problems.
 * ─────────────────────────────────────────────────────────────────────────────
 */

const express = require("express");
const router = express.Router();
const statisticsService = require("../services/statisticsService");
const PDFDocument = require("pdfkit");

/**
 * services/statisticsPdfService.js
 * -----------------------------------------------------------------------------
 * Server-side PDF generator for the Statistics report.
 * Uses PDFKit, which is already included in package.json.
 * -----------------------------------------------------------------------------
 */

const PAGE = {
  margin: 42,
  bottom: 54,
};

function num(value, digits = 2) {
  return (Number(value) || 0).toFixed(digits);
}

function txt(value, fallback = "-") {
  if (value === null || value === undefined || value === "") return fallback;
  return String(value);
}

function dateText(value) {
  if (!value) return "-";
  const d = value instanceof Date ? value : new Date(value);
  if (Number.isNaN(d.getTime())) return "-";
  return d.toLocaleDateString("en-GB");
}

function money(value) {
  return num(value, 2);
}

function addHeader(doc, subtitle) {
  const top = PAGE.margin;
  doc
    .font("Helvetica-Bold")
    .fontSize(20)
    .fillColor("#111827")
    .text("Production Hall Statistics Report", PAGE.margin, top, {
      align: "left",
    });

  doc
    .font("Helvetica")
    .fontSize(9)
    .fillColor("#6b7280")
    .text(subtitle || "", PAGE.margin, top + 26, { align: "left" });

  doc
    .moveTo(PAGE.margin, top + 44)
    .lineTo(doc.page.width - PAGE.margin, top + 44)
    .strokeColor("#d1d5db")
    .lineWidth(0.8)
    .stroke();

  doc.y = top + 60;
}

function addFooter(doc) {
  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i += 1) {
    doc.switchToPage(i);
    const pageNumber = i + 1;
    const y = doc.page.height - 36;
    doc
      .moveTo(PAGE.margin, y - 8)
      .lineTo(doc.page.width - PAGE.margin, y - 8)
      .strokeColor("#e5e7eb")
      .lineWidth(0.5)
      .stroke();
    doc
      .font("Helvetica")
      .fontSize(8)
      .fillColor("#6b7280")
      .text(
        `Generated by Production Hall - Page ${pageNumber}`,
        PAGE.margin,
        y,
        {
          align: "center",
          width: doc.page.width - PAGE.margin * 2,
        },
      );
  }
}

function ensureSpace(doc, height) {
  if (doc.y + height > doc.page.height - PAGE.bottom) {
    doc.addPage();
    doc.y = PAGE.margin;
  }
}

function section(doc, title) {
  ensureSpace(doc, 34);
  doc.moveDown(0.55);
  doc
    .font("Helvetica-Bold")
    .fontSize(13)
    .fillColor("#0f172a")
    .text(title, PAGE.margin, doc.y);
  doc
    .moveTo(PAGE.margin, doc.y + 4)
    .lineTo(doc.page.width - PAGE.margin, doc.y + 4)
    .strokeColor("#cbd5e1")
    .lineWidth(0.6)
    .stroke();
  doc.moveDown(0.8);
}

function drawKeyValues(doc, items, columns = 4) {
  const usableWidth = doc.page.width - PAGE.margin * 2;
  const gap = 8;
  const boxWidth = (usableWidth - gap * (columns - 1)) / columns;
  const boxHeight = 52;
  let x = PAGE.margin;
  let y = doc.y;

  items.forEach((item, index) => {
    if (index > 0 && index % columns === 0) {
      x = PAGE.margin;
      y += boxHeight + gap;
    }
    ensureSpace(doc, boxHeight + 12);
    doc
      .roundedRect(x, y, boxWidth, boxHeight, 5)
      .fillAndStroke("#f8fafc", "#e5e7eb");
    doc
      .font("Helvetica")
      .fontSize(8.5)
      .fillColor("#64748b")
      .text(item.label, x + 9, y + 8, { width: boxWidth - 18, height: 16 });
    doc
      .font("Helvetica-Bold")
      .fontSize(14)
      .fillColor("#0f172a")
      .text(txt(item.value), x + 9, y + 25, { width: boxWidth - 18 });
    x += boxWidth + gap;
  });

  doc.y = y + boxHeight + 14;
}

function stringHeight(doc, value, width, fontSize = 8) {
  return doc
    .font("Helvetica")
    .fontSize(fontSize)
    .heightOfString(txt(value), { width, align: "left" });
}

function drawTable(doc, columns, rows, options = {}) {
  const usableWidth = doc.page.width - PAGE.margin * 2;
  const widths = columns.map((c) => c.width || 1);
  const totalWeight = widths.reduce((s, w) => s + w, 0);
  const actualWidths = widths.map((w) => (w / totalWeight) * usableWidth);
  const title = options.title;
  const maxRows = options.maxRows || rows.length;
  const dataRows = (rows || []).slice(0, maxRows);

  if (title) {
    ensureSpace(doc, 26);
    doc
      .font("Helvetica-Bold")
      .fontSize(10)
      .fillColor("#111827")
      .text(title, PAGE.margin, doc.y);
    doc.moveDown(0.4);
  }

  if (!dataRows.length) {
    ensureSpace(doc, 20);
    doc
      .font("Helvetica-Oblique")
      .fontSize(9)
      .fillColor("#6b7280")
      .text(options.emptyText || "No data available.", PAGE.margin, doc.y);
    doc.moveDown(0.6);
    return;
  }

  const drawHeader = () => {
    ensureSpace(doc, 28);
    const y = doc.y;
    let x = PAGE.margin;
    doc.rect(PAGE.margin, y, usableWidth, 20).fill("#e2e8f0");
    columns.forEach((col, i) => {
      doc
        .font("Helvetica-Bold")
        .fontSize(7.5)
        .fillColor("#111827")
        .text(col.label, x + 4, y + 6, {
          width: actualWidths[i] - 8,
          align: col.align || "left",
        });
      x += actualWidths[i];
    });
    doc.y = y + 20;
  };

  drawHeader();

  dataRows.forEach((row, rowIndex) => {
    const cellHeights = columns.map((col, i) =>
      stringHeight(doc, row[col.key], actualWidths[i] - 8, 8),
    );
    const rowHeight = Math.max(18, Math.max(...cellHeights) + 10);
    ensureSpace(doc, rowHeight + 24);
    if (doc.y < PAGE.margin + 3) drawHeader();

    const y = doc.y;
    if (rowIndex % 2 === 0) {
      doc.rect(PAGE.margin, y, usableWidth, rowHeight).fill("#f8fafc");
    }

    let x = PAGE.margin;
    columns.forEach((col, i) => {
      doc
        .font("Helvetica")
        .fontSize(8)
        .fillColor("#111827")
        .text(txt(row[col.key]), x + 4, y + 5, {
          width: actualWidths[i] - 8,
          align: col.align || "left",
        });
      x += actualWidths[i];
    });

    doc
      .moveTo(PAGE.margin, y + rowHeight)
      .lineTo(doc.page.width - PAGE.margin, y + rowHeight)
      .strokeColor("#e5e7eb")
      .lineWidth(0.4)
      .stroke();
    doc.y = y + rowHeight;
  });

  if ((rows || []).length > maxRows) {
    doc
      .font("Helvetica-Oblique")
      .fontSize(8)
      .fillColor("#6b7280")
      .text(
        `Showing first ${maxRows} of ${rows.length} rows.`,
        PAGE.margin,
        doc.y + 5,
      );
    doc.moveDown(0.8);
  } else {
    doc.moveDown(0.8);
  }
}

function productCostRows(rows) {
  return (rows || []).map((c) => ({
    name: c.name,
    baseCost: money(c.unitCost),
    loadedCost: money(c.fullyLoadedUnitCost || c.unitCost),
    stock: num(c.stock, 2),
    stockValue: money(c.stockValue),
  }));
}

function createStatisticsReportPdf({ stats, purchaseOrder, productionTasks }) {
  const doc = new PDFDocument({
    size: "A4",
    margin: PAGE.margin,
    bufferPages: true,
    info: {
      Title: "Production Hall Statistics Report",
      Author: "Production Hall",
      Subject: "Statistics report",
    },
  });

  const generated = new Date(stats.generatedAt || Date.now());
  addHeader(
    doc,
    `Generated ${generated.toLocaleString("en-GB")} | Analysis window: ${stats.windowDays || 0} day(s)`,
  );

  section(doc, "At-a-glance Summary");
  drawKeyValues(doc, [
    { label: "Primary Products", value: stats.counts?.primary || 0 },
    { label: "Secondary Products", value: stats.counts?.secondary || 0 },
    { label: "Tertiary Products", value: stats.counts?.tertiary || 0 },
    { label: "Activity Records", value: stats.counts?.logs || 0 },
    { label: "First Activity Date", value: dateText(stats.firstDate) },
    { label: "Safe Stock Target", value: `${stats.safeStockDays || 0} days` },
    {
      label: "Total Inventory Value",
      value: money(stats.costs?.totals?.totalInventoryValue),
    },
    {
      label: "Consumed Material Cost",
      value: money(stats.consumedMaterialCost),
    },
  ]);

  section(doc, "Cost Per Unit - Materials, Overhead and Labour");
  if (stats.costing) {
    drawKeyValues(doc, [
      { label: "Produced Units", value: num(stats.costing.unitsProduced, 2) },
      {
        label: "Material / Unit Avg",
        value: money(stats.costing.perUnit?.material),
      },
      {
        label: "Overhead / Unit",
        value: money(stats.costing.perUnit?.overhead),
      },
      { label: "Labour / Unit", value: money(stats.costing.perUnit?.labor) },
      {
        label: "Fully Loaded / Unit",
        value: money(stats.costing.perUnit?.fullyLoaded),
      },
      { label: "Overhead Total", value: money(stats.costing.overhead?.total) },
      { label: "Labour Total", value: money(stats.costing.labor?.total) },
      {
        label: "Attendance Days",
        value: stats.costing.labor?.attendanceDays || 0,
      },
    ]);
  } else {
    doc
      .font("Helvetica-Oblique")
      .fontSize(9)
      .fillColor("#6b7280")
      .text("No costing data available.");
  }

  section(doc, "Production Cost Analysis");
  drawTable(
    doc,
    [
      { key: "name", label: "Secondary Product", width: 2.4 },
      { key: "baseCost", label: "Base Cost", align: "right" },
      { key: "loadedCost", label: "Loaded Cost", align: "right" },
      { key: "stock", label: "Stock", align: "right" },
      { key: "stockValue", label: "Stock Value", align: "right" },
    ],
    productCostRows(stats.costs?.secondaryCosts),
    { title: "Secondary Products", emptyText: "No secondary products." },
  );
  drawTable(
    doc,
    [
      { key: "name", label: "Tertiary Product", width: 2.4 },
      { key: "baseCost", label: "Base Cost", align: "right" },
      { key: "loadedCost", label: "Loaded Cost", align: "right" },
      { key: "stock", label: "Stock", align: "right" },
      { key: "stockValue", label: "Stock Value", align: "right" },
    ],
    productCostRows(stats.costs?.tertiaryCosts),
    { title: "Tertiary Products", emptyText: "No tertiary products." },
  );

  section(doc, "Consumption, Damage and Stock");
  drawKeyValues(doc, [
    {
      label: "Avg Daily Primary Use",
      value: num(stats.consumptionRates?.daily, 2),
    },
    {
      label: "Primary Used - Last 7 Days",
      value: num(stats.consumptionRates?.weekly, 2),
    },
    {
      label: "Primary Used - Last 30 Days",
      value: num(stats.consumptionRates?.monthly, 2),
    },
    { label: "Primary Damaged", value: num(stats.damageTotals?.primary, 2) },
    {
      label: "Secondary Damaged",
      value: num(stats.damageTotals?.secondary, 2),
    },
    { label: "Tertiary Damaged", value: num(stats.damageTotals?.tertiary, 2) },
    { label: "Damage Cost - Primary", value: money(stats.damageCost) },
    {
      label: "Primary Stock Total",
      value: num(stats.stockLevels?.primaryTotal, 2),
    },
  ]);

  drawTable(
    doc,
    [
      { key: "name", label: "Primary Product", width: 2.1 },
      { key: "price", label: "Unit Price", align: "right" },
      { key: "currentStock", label: "Stock", align: "right" },
      { key: "avgDaily", label: "Avg Daily", align: "right" },
      { key: "consumed7", label: "7d Use", align: "right" },
      { key: "consumed30", label: "30d Use", align: "right" },
      { key: "coverage", label: "Coverage", align: "right" },
      { key: "status", label: "Status", align: "center" },
    ],
    (stats.primaryStats || []).map((p) => ({
      name: p.name,
      price: p.hasPrice ? money(p.price) : "No price",
      currentStock: num(p.currentStock, 2),
      avgDaily: num(p.avgDaily, 2),
      consumed7: num(p.consumed7, 2),
      consumed30: num(p.consumed30, 2),
      coverage: p.coverageDays === null ? "-" : `${p.coverageDays} d`,
      status: p.belowSafe
        ? "Below safe"
        : p.coverageDays === null
          ? "No usage"
          : "OK",
    })),
    { title: "Primary Product Consumption and Coverage" },
  );

  drawTable(
    doc,
    [
      { key: "day", label: "Date" },
      { key: "primary", label: "Primary", align: "right" },
      { key: "secondary", label: "Secondary", align: "right" },
      { key: "tertiary", label: "Tertiary", align: "right" },
      { key: "damaged", label: "Damaged", align: "right" },
    ],
    (stats.dailyProduction || [])
      .slice()
      .reverse()
      .map((d) => ({
        day: d.day,
        primary: num(d.primary, 2),
        secondary: num(d.secondary, 2),
        tertiary: num(d.tertiary, 2),
        damaged: num(d.damaged, 2),
      })),
    { title: "Daily Production and Inventory Movement - Last 30 Active Days" },
  );

  section(doc, "Purchase Order Recommendation - Primary Products");
  drawKeyValues(
    doc,
    [
      {
        label: "Coverage Period",
        value: `${purchaseOrder?.coverageDays || 0} days`,
      },
      {
        label: "Products Need Ordering",
        value: purchaseOrder?.orderNeededCount || 0,
      },
      {
        label: "Estimated Order Cost",
        value: money(purchaseOrder?.totalEstimatedCost),
      },
    ],
    3,
  );
  drawTable(
    doc,
    [
      { key: "name", label: "Primary Product", width: 2.2 },
      { key: "avgDaily", label: "Avg Daily", align: "right" },
      { key: "currentStock", label: "Stock", align: "right" },
      { key: "required", label: "Needed", align: "right" },
      { key: "order", label: "Order Qty", align: "right" },
      { key: "cost", label: "Est. Cost", align: "right" },
      { key: "status", label: "Status", align: "center" },
    ],
    (purchaseOrder?.items || []).map((i) => ({
      name: i.name,
      avgDaily: num(i.avgDaily, 2),
      currentStock: num(i.currentStock, 2),
      required: num(i.requiredForPeriod, 2),
      order: num(i.recommendedOrder, 2),
      cost: i.hasPrice ? money(i.estimatedCost) : "No price",
      status: i.noData
        ? "No usage"
        : i.sufficient
          ? "Sufficient"
          : "Order needed",
    })),
  );

  section(doc, "Daily Production Task Recommendation");
  drawKeyValues(
    doc,
    [
      {
        label: "Target Coverage",
        value: `${productionTasks?.targetDays || 0} days`,
      },
      {
        label: "Products Need Production",
        value: productionTasks?.actionCount || 0,
      },
    ],
    2,
  );
  drawTable(
    doc,
    [
      { key: "name", label: "Product", width: 2.2 },
      { key: "tier", label: "Tier" },
      { key: "currentStock", label: "Stock", align: "right" },
      { key: "avgDaily", label: "Avg Daily", align: "right" },
      { key: "required", label: "Required", align: "right" },
      { key: "shortage", label: "Shortage", align: "right" },
      { key: "produce", label: "Produce", align: "right" },
      { key: "action", label: "Action", align: "center" },
    ],
    (productionTasks?.tasks || []).map((t) => ({
      name: t.name,
      tier: t.tier,
      currentStock: num(t.currentStock, 2),
      avgDaily: num(t.avgDaily, 2),
      required: num(t.requiredStock, 2),
      shortage: num(t.shortage, 2),
      produce: num(t.suggestedProduction, 2),
      action: t.noData
        ? "No usage"
        : t.needsProduction
          ? "Produce"
          : "No action",
    })),
  );

  if (stats.workerRanking && stats.workerRanking.length) {
    section(doc, "Worker Performance Ranking");
    drawTable(
      doc,
      [
        { key: "rank", label: "#", align: "center", width: 0.5 },
        { key: "name", label: "Worker", width: 2 },
        { key: "role", label: "Role" },
        { key: "tasks", label: "Tasks", align: "right" },
        { key: "batches", label: "Batches", align: "right" },
        { key: "quality", label: "Quality", align: "right" },
        { key: "errors", label: "Errors", align: "right" },
        { key: "score", label: "Score", align: "right" },
      ],
      stats.workerRanking.map((w, index) => ({
        rank: index + 1,
        name: w.name,
        role: w.role || "-",
        tasks: w.tasksCompleted || 0,
        batches: w.batchesMade || 0,
        quality: w.qualityRounds || 0,
        errors: w.errors || 0,
        score: w.score || 0,
      })),
    );
  }

  if (stats.costs?.missingPriceWarnings?.length) {
    section(doc, "Warnings");
    doc
      .font("Helvetica")
      .fontSize(9)
      .fillColor("#92400e")
      .text(
        `Missing primary prices: ${stats.costs.missingPriceWarnings.join(", ")}. Costs using these products may be understated.`,
        PAGE.margin,
        doc.y,
        { width: doc.page.width - PAGE.margin * 2 },
      );
  }

  return doc;
}

// ── GET /statistics — full dashboard ─────────────────────────────────────────
router.get("/", async (req, res) => {
  try {
    const stats = await statisticsService.getStatistics();
    // Pre-load a default purchase order (30 days) and production tasks (14 days)
    // so the page is useful on first load without an extra request.
    const [purchaseOrder, productionTasks] = await Promise.all([
      statisticsService.getPurchaseOrder(30),
      statisticsService.getProductionTasks(statisticsService.SAFE_STOCK_DAYS),
    ]);
    res.render("statistics", {
      title: "Statistics",
      stats,
      purchaseOrder,
      productionTasks,
      error: null,
    });
  } catch (error) {
    res.render("statistics", {
      title: "Statistics",
      stats: null,
      purchaseOrder: null,
      productionTasks: null,
      error: error.message,
    });
  }
});

// ── GET /statistics/report.pdf — printable PDF statistics report ─────────────
router.get("/report.pdf", async (req, res) => {
  try {
    const coverageDays = Math.max(
      1,
      parseInt(req.query.coverageDays || req.query.poDays, 10) || 30,
    );
    const taskDays = Math.max(
      1,
      parseInt(req.query.taskDays, 10) || statisticsService.SAFE_STOCK_DAYS,
    );

    const [stats, purchaseOrder, productionTasks] = await Promise.all([
      statisticsService.getStatistics(),
      statisticsService.getPurchaseOrder(coverageDays),
      statisticsService.getProductionTasks(taskDays),
    ]);

    const reportDate = new Date().toISOString().slice(0, 10);
    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      `inline; filename="statistics-report-${reportDate}.pdf"`,
    );

    const pdf = createStatisticsReportPdf({
      stats,
      purchaseOrder,
      productionTasks,
    });
    pdf.pipe(res);
    pdf.end();
  } catch (error) {
    console.error("Failed to generate statistics PDF:", error);
    res.status(500).send(`Failed to generate statistics PDF: ${error.message}`);
  }
});

// ── GET /statistics/purchase-order — JSON, parameterised by coverage days ─────
router.get("/purchase-order", async (req, res) => {
  try {
    const days = parseInt(req.query.days, 10) || 30;
    const result = await statisticsService.getPurchaseOrder(days);
    res.json(result);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// ── GET /statistics/production-tasks — JSON, parameterised by target days ─────
router.get("/production-tasks", async (req, res) => {
  try {
    const days =
      parseInt(req.query.days, 10) || statisticsService.SAFE_STOCK_DAYS;
    const result = await statisticsService.getProductionTasks(days);
    res.json(result);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

module.exports = router;
